---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-cluster
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.configs."mysticstorage.local:8443".tls]
      insecure_skip_verify = true
nodes:
  - role: control-plane
    image: kindest/node:v1.28.7
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # Ingress
      - containerPort: 80
        hostPort: 80
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        listenAddress: "0.0.0.0"
        protocol: TCP
